# Main Colors
unrecognized_file: blue
recognized_file:   white
executable_file:   green
dir:               orange

# Link
dead_link: red
link:      cyan

# special files
socket:    green
blockdev:  green
chardev:   green

# Access Modes
write:     darkkhaki
read:      limegreen
exec:      red
no_access: indianred

# Age
day_old:     mediumspringgreen
hour_old:    lime
no_modifier: seagreen

# File Size
file_large:  orange
file_medium: yellow
file_small:  peachpuff

# Random
report: white
user:   moccasin
tree:   cyan
empty:  yellow
error:  red
normal: darkkhaki
inode: moccasin

# Git
addition:     cyan
modification: yellow
deletion:     red
untracked:    blue
unchanged:    green
