#!/bin/sh

bspc rule -r "*"

bar="polybar"

if [[ $bar == "polybar" ]]; then
  killall gnome-panel
  polybar=$(pgrep -x polybar > /dev/null && echo "Process found" || echo "Process not found")
  if [[ $polybar == "Process not found" ]]; then
    $HOME/.config/polybar/launch.sh &
  fi
elif [[ $bar == "gnome-panel" ]]; then
  killall polybar
  gnome-panel &
fi

# Get the first HDMI output name and assign it to a variable
HDMI_OUTPUT=$(xrandr --listmonitors | grep -o 'HDMI[^ ]*' | head -n 1)
EDP_OUTPUT=$(xrandr --listmonitors | grep -o 'eDP[^ ]*' | head -n 1)

# screenlayout="external-top"
screenlayout="right"

if [[ $(xrandr -q | grep "$HDMI_OUTPUT" | grep -oP "$HDMI_OUTPUT \K\w+") == "connected" ]]; then
  killall btops
  if [[ $screenlayout == 'left' ]]; then
    $HOME/.screenlayout/leftScreen.sh
    bspc monitor $EDP_OUTPUT -d 2 3 4 5 6 7 8 9 10
    bspc monitor $HDMI_OUTPUT -d 1
  elif [[ $screenlayout == 'right' ]]; then
    $HOME/.screenlayout/rightScreen.sh
    bspc monitor $EDP_OUTPUT -d 1
    bspc monitor $HDMI_OUTPUT -d 2 3 4 5 6 7 8 9 10
  elif [[ $screenlayout == 'kietem' ]]; then
    $HOME/.screenlayout/kietem.sh
    bspc monitor $EDP_OUTPUT -d 1
    bspc monitor $HDMI_OUTPUT -d 2 3 4 5 6 7 8 9
  elif [[ $screenlayout == 'onescreen' ]]; then
    $HOME/.screenlayout/onescreen.sh
    # bspc monitor $EDP_OUTPUT -d 1
    btops &
  elif [[ $screenlayout == 'external-top' ]]; then
    $HOME/.screenlayout/external-top.sh
  else
    $HOME/.screenlayout/rightScreen.sh
    bspc monitor $EDP_OUTPUT -d 1 2 3 4 5 6 7 8
    bspc monitor $HDMI_OUTPUT -d 9 10
  fi
else
  bspc monitor $EDP_OUTPUT -d 1 2 3 4 5 6 7 8 9 10
  killall btops
  btops & # run in background for the other command
fi

pgrep -x picom > /dev/null || picom &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         1
bspc config -m $EDP_OUTPUT window_gap           10

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config automatic_scheme alternate
bspc config automatic_scheme @remove alternate

# Only apply this rule for main monitor of laptop
bspc config -m $EDP_OUTPUT top_padding 38
bspc config -m $EDP_OUTPUT left_padding 10
bspc config -m $EDP_OUTPUT right_padding 10
bspc config -m $EDP_OUTPUT bottom_padding 10
# This is for the second monitor
bspc config -m $HDMI_OUTPUT top_padding 32
bspc config -m $HDMI_OUTPUT left_padding 8
bspc config -m $HDMI_OUTPUT right_padding 8
bspc config -m $HDMI_OUTPUT bottom_padding 8

# border color
bspc config normal_border_color "#3b3f4c"
bspc config active_border_color "#777777"

bspc config focused_border_color '#ffd866'

bspc config presel_feedback_color "#6272a4"

# movie and resize window with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_motion_interval 0
# bspc config pointer_action2 resize_corner
bspc config honor_size_hints true
# bspc config ignore_ewh_struts polybar

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

########################################################
############       BSPC RULE       #####################
########################################################
## Make all windows floating by default
bspc rule -a '*' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a kitty state=tiled
bspc rule -a Brave-browser state=tiled

# always floating gui for python
bspc rule -a Conky-manager state=floating
bspc rule -a Tk state=floating
bspc rule -a com-sun-tools-javac-launcher-Main state=floating
bspc rule -a flameshot state=floating
bspc rule -a Gpick state=floating
bspc rule -a Main_meeting state=floating
bspc rule -a Meeting state=floating
bspc rule -a Deno state=tiled
bspc rule -a Ulauncher border=off state=floating
bspc rule -a Protonvpn border=on state=floating center=on
bspc rule -a photoshop.exe border=on state=floating
bspc rule -a Postman state=floating

# bspc rule -a \* rectangle 800x600+0+0 center=true

bspc config external_rules_command ~/.config/bspwm/src/float_AndroidEmulator.sh

# fix X cursor to default
xsetroot -cursor_name left_ptr &
