#!/bin/sh

bspc rule -r "*"

bar="polybar"

if [[ $bar == "polybar" ]]; then
  killall gnome-panel
  polybar=$(pgrep -x polybar > /dev/null && echo "Process found" || echo "Process not found")
  if [[ $polybar == "Process not found" ]]; then
    # ~/.config/bspwm/src/start-polybar.sh &
    $HOME/.config/polybar/launch.sh &
  fi
elif [[ $bar == "gnome-panel" ]]; then
  killall polybar
  gnome-panel &
fi

screenlayout="kietem"

if [[ $(xrandr -q | grep 'HDMI' | grep -oP 'HDMI-1 \K\w+') == "connected" ]]; then
  killall btops
  if [[ $screenlayout == 'left' ]]; then
    $HOME/.screenlayout/leftScreen.sh
    bspc monitor eDP -d 2 3 4 5 6 7 8 9 10
    bspc monitor HDMI-A-0 -d 1
  elif [[ $screenlayout == 'kietem' ]]; then
    $HOME/.screenlayout/kietem.sh
    bspc monitor eDP-1 -d 1
    bspc monitor HDMI-1 -d 2 3 4 5 6 7 8 9
  elif [[ $screenlayout == 'kietem_onescreen' ]]; then
    $HOME/.screenlayout/kietem_onescreen.sh
    # bspc monitor eDP-1 -d 1
    btops &
  else
    $HOME/.screenlayout/rightScreen.sh
    bspc monitor eDP -d 1 2 3 4 5 6 7 8
    bspc monitor HDMI-A-0 -d 9 10
    # bspc monitor eDP -d 1
    # bspc monitor HDMI-A-0 -d 2 3 4 5 6 7 8 9 10
  fi
else
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
  killall btops
  btops & # run in background for the other command
fi

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backends &

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding 38
bspc config left_padding 10
bspc config right_padding 10
bspc config bottom_padding 10
bspc config automatic_scheme alternate
bspc config automatic_scheme @remove alternate

# border color
bspc config normal_border_color "#3b3f4c"
bspc config active_border_color "#777777"

bspc config focused_border_color '#ffffff'

bspc config presel_feedback_color "#6272a4"

# movie and resize window with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_motion_interval 0
# bspc config pointer_action2 resize_corner
bspc config honor_size_hints true
# bspc config ignore_ewh_struts polybar

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

########################################################
############       BSPC RULE       #####################
########################################################
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a kitty state=tiled

# always floating gui for python
bspc rule -a Conky-manager state=floating
bspc rule -a Tk state=floating
bspc rule -a com-sun-tools-javac-launcher-Main state=floating
bspc rule -a flameshot state=floating
bspc rule -a Gpick state=floating
bspc rule -a Deno state=tiled
bspc rule -a Ulauncher border=off state=floating
bspc rule -a Protonvpn border=on state=floating center=on
bspc rule -a photoshop.exe border=on state=floating

# bspc rule -a \* rectangle 800x600+0+0 center=true

bspc config external_rules_command ~/.config/bspwm/src/float_AndroidEmulator.sh

# fix X cursor to default
xsetroot -cursor_name left_ptr &
