#!/bin/sh

# TERM=/usr/bin/kitty
# EDITOR=/usr/local/bin/nvim
# BROWSER=/usr/bin/brave
userresources=$HOME/.config/xinit/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
_NET_CURRENT_DESKTOP=0

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

source $HOME/.config/xinit/xprofile
# source $HOME/.config/xinit/Xresources

export ANTLR_JAR=$HOME/Downloads/antlr-4.9.2-complete.jar
export GDK_BACKEND=x11

# exec i3
exec bspwm
